### ISSUE TITLE
Migration error: Unknown type keyspace.serial: ""

### ISSUE THREAD

**Issue by frm** [cafebazaar/ecto-cassandra#1]
I tried to run a migration on a project and this error came up:

```
18:53:33.972 [info]  == Running Atmos.SensorRepo.Migrations.CreateSensorReadings.change/0 forward

18:53:33.972 [info]  create table sensor_readings
** (CQL.Error) [invalid] Unknown type atmos_dev.serial: ""
    lib/ecto_cassandra/adapter.ex:26: EctoCassandra.Adapter.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:127: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:73: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/migrator.ex:250: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:84: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

The project uses two repos: `Atmos.Repo` is the default postgres one, `Atmos.SensorRepo` is the one running the `EctoCassandra` adapter. Migrations on the former run smoothly. I tried checking if the `Adapter` module is running the migration on the correct repo and it is.

Here's the migration:

```elixir
defmodule Atmos.SensorRepo.Migrations.CreateSensorReadings do
  use Ecto.Migration

  @clustering_order "WITH CLUSTERING ORDER BY (timestamp DESC)"

  def change do
    create table(:sensor_readings, options: @clustering_order) do
      add :team_id, :integer, partition_key: true
      add :sensor_id, :integer, partition_key: true
      add :type, :string
      add :value, :float
      add :timestamp, :timestamp, clustering_column: true

      timestamps()
    end
  end
end
```

I don't know if it helps but I'm running macOS Sierra 10.12.3 and Elixir 1.4.2.

**Comment by frm** [comment]
Ok, so I've gotten into this.

Here's the resulting CQL:
```cql
CREATE TABLE sensor_readings (
  id serial,
  team_id int,
  box_id int,
  type text,
  value double,
  timestamp timestamp,
  inserted_at timestamp,
  updated_at timestamp,
  PRIMARY KEY ((id, team_id, box_id), timestamp)
) WITH CLUSTERING ORDER BY (timestamp DESC)
```

This happens because `Ecto`, [by default adds a primary_key `id` of type `serial`](https://hexdocs.pm/ecto/Ecto.Migration.html#create/2).

I'd be down for making a fix that prunes this assumption since Cassandra does not have a `serial` data type, if you think it's worth it.

Btw, I resolved the issue by adding `primary_key: false` to the `table(...)`.

**Comment by hzamani** [comment]
Thanks
