### ISSUE TITLE
Occasional errors

### ISSUE THREAD

**Issue by vfsoraki** [cafebazaar/ecto-cassandra#15]
I get this error occasionally:

```
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :ok
        (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:68: Ecto.Repo.Queryable.one/4
```

Tracing it back, `lib/ecto/repo/queryable.ex:130`:

```elixir
  defp execute(operation, repo, adapter, query, opts) when is_list(opts) do
    {meta, prepared, params} = Planner.query(query, operation, repo, adapter, 0)

    case meta do
      %{fields: nil} ->
        adapter.execute(repo, meta, prepared, params, nil, opts)
      %{select: select, fields: fields, prefix: prefix, take: take,
        sources: sources, assocs: assocs, preloads: preloads} ->
        preprocess    = preprocess(prefix, sources, adapter)
        {count, rows} = adapter.execute(repo, meta, prepared, params, preprocess, opts) # THIS LINE
        postprocess   = postprocess(select, fields, take)
        {_, take_0}   = Map.get(take, 0, {:any, %{}})
        {count,
          rows
          |> Ecto.Repo.Assoc.query(assocs, sources)
          |> Ecto.Repo.Preloader.query(repo, preloads, take_0, postprocess, opts)}
    end
  end
```

And knowing adapter is this library, `adapter.ex`:

```elixir
  def execute(repo, %{fields: fields} = meta, query, params, process, options) do
    [cql, options] = super(repo, meta, query, params, process, options)

    case exec_and_log(repo, cql, options) do
      %CQL.Result.Rows{rows_count: count, rows: rows} ->
        {count, Enum.map(rows, &process_row(&1, fields, process))}
      %CQL.Result.Void{} -> :ok # THIS LINE
      error              -> raise error
    end
  end
```

So, if result is `%CQL.Result.Void{}`, returning `:ok` throws a match error.

I can fix this, returning `{0, []}` should be enough, yes?

**Comment by alirajabi** [comment]
I recommend using cassandra 3.10 and please give us more information like your query.
I saw `ecto execute` function does not force return {0, []} and accepts `:no_return`.

**Comment by vfsoraki** [comment]
Sorry for being late.
I am using `3.11`. I can't provide more information now, as I have switched to my own fork which has these fixes.
Maybe sometimes later, I can test with your repo. I will let you know.

**Comment by alirajabi** [comment]
Your issue is resolved on last version.
I saw your code, your fix is harmless but i found the problem occurs when connection process does not kill after error

https://github.com/cafebazaar/elixir-cassandra/commit/cce0c62dc991c4ceb5b2cba885689e7e44017b59
