### ISSUE TITLE
How to use cassandra's map with ecto-cassandra?

### ISSUE THREAD

**Issue by sureshprasanna70** [cafebazaar/ecto-cassandra#24]
I am trying to create a collection for which a cql query looks like this.

`create table groups (admin_id int, participants map<text, integer>);`

My schema looks like this 
```
defmodule HelloWorld.Repo.Migrations.CreateGroups do
  use Ecto.Migration

  def change do
    create table(:groups) do
      add :admin_id, :integer
      add :participants, {:map,"<text,integer>"}

      timestamps()
    end

  end
end
```

When I run `mix ecto.migrate`, I'm getting 

```** (FunctionClauseError) no function clause matching in Ecto.Migration.validate_type!/1

    The following arguments were given to Ecto.Migration.validate_type!/1:

        # 1
        {:map, "<text,integer>"}

    Attempted function clauses (showing 4 out of 4):

        defp validate_type!(type) when is_atom(type)
        defp validate_type!({type, subtype}) when is_atom(type) and is_atom(subtype)
        defp validate_type!({type, subtype}) when is_atom(type) and is_tuple(subtype)
        defp validate_type!(%Ecto.Migration.Reference{} = reference)

    (ecto) lib/ecto/migration.ex:800: Ecto.Migration.validate_type!/1
    (ecto) lib/ecto/migration.ex:617: Ecto.Migration.add/3
```
Any pointers will be appreciated..

**Comment by alirajabi** [comment]
https://github.com/cafebazaar/ecto-cassandra/issues/10
